CREATE TABLE medical_history (
    id BIGSERIAL PRIMARY KEY,
    allergic BOOLEAN,
    allergic_to VARCHAR(255),
    footwear_type VARCHAR(100),
    footwear_number VARCHAR(10),
    main_complaint TEXT,
    lower_limb_surgery BOOLEAN,
    surgery_details TEXT,
    practices_sports BOOLEAN,
    sport_type VARCHAR(100),
    sport_frequency VARCHAR(100),
    sport_footwear VARCHAR(100),
    uses_medication BOOLEAN,
    medication_details TEXT,
    pregnant BOOLEAN,
    pain_sensitivity VARCHAR(50),
    hypertension BOOLEAN,
    heart_disease BOOLEAN,
    seizures BOOLEAN,
    hepatitis BOOLEAN,
    kidney_disease BOOLEAN,
    hemodialysis BOOLEAN,
    varicose_veins BOOLEAN,
    peripheral_neuropathy BOOLEAN,
    smoker BOOLEAN,
    psoriasis BOOLEAN,
    oncological_history BOOLEAN,
    vascular_impairment BOOLEAN,
    pacemaker_or_pins BOOLEAN
);
